### PR TITLE
Depend on cider / nrepl-client.el instead of nrepl

### PR DESCRIPTION
**Pull request by purcell**
Untested, but this is the least that is going to need changing.

Would it also be worth moving this repo across to the `clojure-emacs` org?

Cheers,

-Steve

### CODE REVIEW

**Comment by dudebout** [comment]
+1 for updating dependency list. `lein` is not package-installable at the moment.

**Comment by purcell** [comment]
Unfortunately the changes in this PR are not yet sufficient for cider compatibility. e.g. it looks like `nrepl-words-of-inspiration` is now `cider-words-of-inspiration`. Let me see if I can fix this PR up...

**Comment by purcell** [comment]
Okay, added some further changes that appear to be necessary, but I'm not in a position right now to test them. @dudebout -- would you mind giving this version a try?

**Comment by dudebout** [comment]
@purcell, I unfortunately do not have a computer set up with clojure. I
just had a problem installing my emacs packages this morning.

**Comment by purcell** [comment]
Okay, I tested it, and it seems to be working. :-)

**Pull request closed without merging**
